### ISSUE TITLE
Dependencies do not transpile for IE11

### ISSUE THREAD

**Issue by therealzteve** [vaadin/base-starter-vue#15]
I downloaded the repo and executed the build command. Afterwards I checked the generated chunk-vendors JS File. 

Even with the transpileDependencies Option there are still Arrow-Functions and other ES6-Features contained in the output. 

This only affects the dependencies. If I add e.g. Arrow Functions in the App Code, they get transpiled correctly.

Could you check this?

Thanks!

**Comment by therealzteve** [comment]
I just found a solution to get the vaadin dependencies transpiled:

In the vue.config.js file I removed the .* part from the regexp and now it works. My vue.config.js file now looks like this:
´
module.exports = {
  transpileDependencies: [/@vaadin/, /@polymer/, /@webcomponents/]
}
´

**Comment by web-padawan** [comment]
Thanks for the issue and please note that this is already fixed by c0e6446a02e9c0772203ca23521936675a0c90e4 on master, as well as `v12` branch. Looks like you have downloaded the older version of the starter.

**Comment by therealzteve** [comment]
Thanks for the reply. I just looked at the commit and saw, that the vue.config.js file contains this transpileDependencies configuration:
`transpileDependencies: [/@vaadin\/.*/, /@polymer\/.*/, /@webcomponents\/.*/]`

This does not transpile the dependencies in my try. However what worked was:
`transpileDependencies: [/@vaadin/, /@polymer/, /@webcomponents/]`

I did the test yesterday with the lastest master version.

**Comment by web-padawan** [comment]
Thanks, will check it out and update the config accordingly.
